spring:
  application:
    name: StockPulse
  # ?????? ??
  datasource:
    url: jdbc:postgresql://localhost:5432/stockpulse
    username: ${DB_USERNAME:your_username}
    password: ${DB_PASSWORD:your_password}
    driver-class-name: org.postgresql.Driver

  # JPA/Hibernate ??
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public

  # Spring Security ?? ?? (??? ??????)
  security:
    user:
      name: admin
      password: ${ADMIN_PASSWORD:admin123}
      roles: ADMIN

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.example: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"