version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: stockpulse-postgres
    env_file:
      - ../properties.env # 관련 환경변수 secret 사용하도록 해야함
    environment:
      POSTGRES_DB: ${DB_SCHEME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - stockpulse-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_SCHEME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  stockpulse-network:
    driver: bridge